export const sample_foods = [
  {
    id: "1",
    name: "Classic Maggi",
    cookTime: "10-15",
    price: 30,
    favorite: false,
    stars: 3.5,
    imageUrl: "Maggie.jpg",
    tags: ["Lunch", "Snack", "FastFood"],
  },
  {
    id: "2",
    name: "Cheese Maggi",
    cookTime: "10-15",
    price: 40,
    favorite: true,
    stars: 4.2,
    imageUrl: "cheese_maggi.jpg",
    tags: ["Lunch", "Snack", "FastFood"],
  },
  {
    id: "3",
    name: "Spicy Masala Maggi",
    cookTime: "10-15",
    price: 35,
    favorite: true,
    stars: 4.3,
    imageUrl: "spicy_maggi.jpg",
    tags: ["Lunch", "Snack", "FastFood"],
  },
  {
    id: "4",
    name: "Butter Maggi",
    cookTime: "10-15",
    price: 38,
    favorite: false,
    stars: 3.9,
    imageUrl: "butter_maggi.jpg",
    tags: ["Lunch", "Snack", "FastFood"],
  },
  {
    id: "5",
    name: "Chole Rice",
    cookTime: "20-30",
    price: 55,
    favorite: true,
    stars: 4.4,
    imageUrl: "chole_rice.jpg",
    tags: ["Lunch", "Indian", "Vegetarian"],
  },
  {
    id: "6",
    name: "Rajma Rice",
    cookTime: "20-30",
    price: 60,
    favorite: true,
    stars: 4.5,
    imageUrl: "rajma_rice.jpg",
    tags: ["Lunch", "Indian", "Vegetarian"],
  },
  {
    id: "7",
    name: "Paneer Tikka",
    cookTime: "15-20",
    price: 70,
    favorite: true,
    stars: 4.2,
    imageUrl: "paneer_tikka.jpg",
    tags: ["Snack", "Appetizer", "Indian"],
  },
  {
    id: "8",
    name: "Noodle Samosa",
    cookTime: "5-10",
    price: 18,
    favorite: true,
    stars: 4.2,
    imageUrl: "noodle_samosa.jpg",
    tags: ["Snack", "StreetFood", "Fusion"],
  },
  {
    id: "9",
    name: "Aloo Paratha",
    cookTime: "20-25",
    price: 40,
    favorite: true,
    stars: 4.5,
    imageUrl: "aloo_paratha.jpg",
    tags: ["Lunch", "Indian", "Vegetarian"],
  },
  {
    id: "10",
    name: "Paneer Paratha",
    cookTime: "20-25",
    price: 50,
    favorite: true,
    stars: 4.6,
    imageUrl: "paneer_paratha.jpg",
    tags: ["Lunch", "Indian", "Vegetarian"],
  },
  {
    id: "11",
    name: "Masala Dosa",
    cookTime: "20-30",
    price: 60,
    favorite: true,
    stars: 4.6,
    imageUrl: "masala_dosa.jpg",
    tags: ["Breakfast", "Indian", "Vegetarian"],
  },
  {
    id: "12",
    name: "Plain Dosa",
    cookTime: "15-20",
    price: 45,
    favorite: false,
    stars: 4.2,
    imageUrl: "plain_dosa.jpg",
    tags: ["Breakfast", "Indian", "Vegetarian"],
  },
  {
    id: "13",
    name: "Onion Dosa",
    cookTime: "20-25",
    price: 55,
    favorite: true,
    stars: 4.5,
    imageUrl: "onion_dosa.jpg",
    tags: ["Breakfast", "Indian", "Vegetarian"],
  },
  {
    id: "14",
    name: "Chole Bhature",
    cookTime: "30-40",
    price: 50,
    favorite: false,
    stars: 4.0,
    imageUrl: "chole_bhature.jpg",
    tags: ["Lunch", "Indian", "Spicy"],
  },
  {
    id: "15",
    name: "Pav Bhaji",
    cookTime: "15-20",
    price: 40,
    favorite: true,
    stars: 4.3,
    imageUrl: "pav_bhaji.jpg",
    tags: ["Snack", "StreetFood", "Vegetarian"],
  },
  {
    id: "16",
    name: "Biryani",
    cookTime: "30-40",
    price: 80,
    favorite: true,
    stars: 4.6,
    imageUrl: "biryani.jpg",
    tags: ["Lunch", "Indian", "Spicy"],
  },
  {
    id: "17",
    name: "Gulab Jamun",
    cookTime: "10-15",
    price: 25,
    favorite: true,
    stars: 4.8,
    imageUrl: "gulab_jamun.jpg",
    tags: ["Dessert", "Indian"],
  },
  {
    id: "18",
    name: "French Fries",
    cookTime: "5-10",
    price: 35,
    favorite: false,
    stars: 4.1,
    imageUrl: "french_fries.jpg",
    tags: ["Snack", "FastFood", "Vegetarian"],
  },
];


export const sample_tags = [
  { name: "All", count: 18 },
  { name: "FastFood", count: 4 },
  { name: "Lunch", count: 9 },
  { name: "SlowFood", count: 0 },
  { name: "Vegetarian", count: 7 },
  { name: "Snack", count: 6 },
  { name: "Dessert", count: 1 },
  { name: "Indian", count: 9 },
  { name: "Spicy", count: 3 },
  { name: "StreetFood", count: 2 },
  { name: "Fusion", count: 1 },
  { name: "Appetizer", count: 1 },
  { name: "Breakfast", count: 4 },
];


export const sample_users=[
  {
    id:1,
   name:'Akhila',
   email:'akhila@gmail.com',
   password:'12345',
   address:'Rohini sec-5',
   isAdmin:true
  },
  {
    id:2,
   name:'RaminderJeet',
   email:'raminderjeet@gmail.com',
   password:'678910',
   address:'Rohini sec-3',
   isAdmin:true
  },
  {
    id:3,
   name:'Gunjan',
   email:'gunjan@gmail.com',
   password:'189245',
   address:'Rithala sec-5',
   isAdmin:true
  },
  {
    id:4,
   name:'Manisha',
   email:'manisha@gmail.com',
   password:'1234abcd',
   address:'Rithala sec-7',
   isAdmin:false
  },
  {
    id:5,
   name:'Ayushi',
   email:'ayushi@gmail.com',
   password:'1290',
   address:'Rithala sec-8',
   isAdmin:false
  }
]
